services:
  service-a:
    build:
      context: ./service_A  # Path to Service A's project directory
      dockerfile: Dockerfile
    ports:
      - "7080:7080"  # Map host port 7080 to container port 7080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SERVICE_B_URL=http://service-b:7081  # Service B's URL within Docker network
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    depends_on:
      - service-b # Ensures Service B starts first
    networks:
      - app-network

  service-b:
    build:
      context: ./service_B  # Path to Service B's project directory
      dockerfile: Dockerfile
    ports:
      - "7081:7081"  # Map host port 7081 to container port 7081
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:serviceBDB
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # Default Docker network driver